---
# tasks file for /root/good-playbook/roles/appconfig
 - name: configure haproxy
   template:
      src:  haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
      mode: 0644
   when: "'frontends' in group_names"
   notify: "{{ webservices }}"
   tags: lb

 - name: create root  directory
   file:
      path: "{{ rootdir }}"
      state: directory
   when: "'apps' in group_names"
   tags: app

 - name: create indexdir
   file:
      path: "{{ indexdir }}"
      state: directory
   when: "'apps' in group_names"
   tags: app


 - name: copy static index.html to tomcat webapps/ansible/index.html
   template:
      src: index.html.j2
      dest: /usr/share/tomcat/webapps/ROOT/index.html
      mode: 0644
   when: "'apps' in group_names"
   tags: app

 - name: copy static index.html to tomcat webapps/ansible/index.html
   copy:
      src: index.html.app1
      dest: /usr/share/tomcat/webapps/ansible/index.html
   when: "'apps' in group_names"
   tags: app

 - name: copy static index.html to tomcat webapps/ansible/index.html
   copy:
      src: index.html.app2
      dest: /usr/share/tomcat/webapps/ansible/index.html
   when: "'apps' in group_names"
   notify: "{{ mwservices }}"
   tags: app
       


 
