---
# tasks file for /root/good-playbook/roles/app1
- name: enable repo
  yum: 
    name: "{{ dbrepo }}"
    state: present
  when: "'appdb' in inventory_hostname"
  tags: db

- name: Install the DB tier
  yum: 
    name: "{{ item }}"
    state: present
  with_items: "{{ db }}"
  when: "'appdb' in inventory_hostname"
  notify: 
      - initialize the DB
      - start db
  tags: db

