---
# vars file for /root/good-playbook/roles/app1
db:
   - 'postgresql10-server'
   - 'postgresql10'

dbservice:
          - 'postgresql10'

dbdir: '/usr/pgsql-10/bin'

dbrepo: 'https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-7-x86_64/pgdg-redhat10-10-1.noarch.rpm'
