---
# handlers file for /root/good-playbook/roles/app1
- name: start webapps
  service: 
    name: "{{ item }}"
    enabled: true
    state: started
  with_items: "{{ webapps }}"

- name: start mwapps
  service: 
    name: "{{ item }}"
    enabled: true
    state: started
  with_items: "{{ mwapps }}"
